### ISSUE TITLE
`objects` vector empty after `read_json`

### ISSUE THREAD

**Issue by Reinaesaya** [alecjacobson/computer-graphics-ray-casting#9] opened 2018-09-24 20:39 UTC
I'm currently debugging my code to see why all my .ppm files are displaying empty black images. I inserted a line in main.cpp right after the read_json script is executed to populate the 'objects' vector:

`// Read a camera and scene description from given .json file`
`read_json(argc<=1?"../shared/data/sphere-and-plane.json":argv[1],camera,objects);`
`std::cout << objects.size()`

I found that the output for this is always `0`, which explains the blank images. Is anyone else encountering this issue???

**Comment by Reinaesaya** [comment] 2018-09-24 20:44
I'm seeing the following warnings when building on Visual Studio. Are they relevant?
![image](https://user-images.githubusercontent.com/6406219/45977961-011a0d00-c019-11e8-97b4-8bc8cb076501.png)

**Comment by psarahdactyl** [comment] 2018-09-25 21:47
Is your program finding the json file?

**Comment by Reinaesaya** [comment] 2018-09-25 22:32
The problem fix has something to do with how Visual Studio builds the project. The 'raycasting.exe' file is actually put into /build/Debug/, not directly into the /build folder.

Hence, you have to manually drag 'raycasting.exe' up to /build and execute it there. Alternatively, change the path from `../shared/data/sphere-and-plane.json` to `../../shared/data/sphere-and-plane.json`.

**Comment by alecjacobson** [comment] 2018-09-26 04:18
Appears to be duplicate of https://github.com/alecjacobson/computer-graphics-ray-casting/issues/5

**Closed as completed by alecjacobson** 2018-09-26 04:18 UTC
